[package]
name = "rusty-tanks"
version = "0.1.0"
authors = ["Robert Pyke <robert.j.pyke@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
specs = "0.16.1"
specs-derive = "0.4"
rand = "0.6"

[dependencies.sdl2]
version = "0.32.1"
default-features = false
features = ["image"]